name: 'pull-request'
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled
      - unlabeled

# TODO: only request needed permissions
permissions: write-all

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # This token will trigger workflow jobs on push
          token: ${{ secrets.GIT_PUSH_TOKEN }}

      - uses: dangoslen/dependabot-changelog-helper@v3
        with:
          activationLabel: 'dependencies'
          changelogPath: './CHANGELOG.md'

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated Changelog\n\n[dependabot skip]"
